version: '3.9'

services:

    rabbitmq-master:
        container_name: rabbitmq-master
        image: rabbitmq:3-management
        hostname: rabbitmq-master
        environment:
            RABBITMQ_ERLANG_COOKIE: MY_SECURITY_COOKIE_HASH_IS_THIS_TEXT
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_VHOST: /
        volumes:
            #- ./.erlang.cookie:/var/lib/rabbitmq/mnesia/.erlang.cookie
            #- ./storage/rabbitmq-master:/var/lib/rabbitmq
            - ./configure-cluster.sh:/usr/local/bin/configure-cluster.sh
        ports:
            - 5673:5672
            - 15673:15672
        networks:
            - cluster-network
        
    rabbitmq-mirror1:
        container_name: rabbitmq-mirror1
        image: rabbitmq:3-management
        hostname: rabbitmq-mirror1
        environment:
            RABBITMQ_ERLANG_COOKIE: MY_SECURITY_COOKIE_HASH_IS_THIS_TEXT
        volumes:
            #- ./.erlang.cookie:/var/lib/rabbitmq/mnesia/.erlang.cookie
            - ./configure-cluster.sh:/usr/local/bin/configure-cluster.sh
        ports:
            - 5674:5672
            - 15674:15672
        depends_on: 
            - rabbitmq-master
        networks:
            - cluster-network

    rabbitmq-mirror2:
        container_name: rabbitmq-mirror2
        image: rabbitmq:3-management
        hostname: rabbitmq-mirror2
        environment:
            RABBITMQ_ERLANG_COOKIE: MY_SECURITY_COOKIE_HASH_IS_THIS_TEXT
        volumes:
            #- ./.erlang.cookie:/var/lib/rabbitmq/mnesia/.erlang.cookie
            - ./configure-cluster.sh:/usr/local/bin/configure-cluster.sh
        ports:
            - 5675:5672
            - 15675:15672
        depends_on: 
            - rabbitmq-master
            - rabbitmq-mirror1
        networks:
            - cluster-network

networks:
    cluster-network:
        driver: bridge
